export const PROCESS_ORDERS = 'PROCESS_ORDERS';
export const PROCESS_ASSETS = 'PROCESS_ASSETS';
export const PROCESS_MARKET = 'PROCESS_MARKET';

export const CACHE_MARKET_DOCUMENTS = 'CACHE_MARKET_DOCUMENTS';
